### PR TITLE
Project compiling fixes

### PR DESCRIPTION
**Pull request by lvonasek**
It is way too hard to contribute due to all the errors after opening the project on Linux and the latest Android Studio.

This PR resolves most of the issues:
* All paths unix compatible
* Gradle version compatible with the latest Android Studio
* Incorrect pointer typing fixed
* Obsolete FLOAT_IS_INVALID replaced with isnan
* Target latest NDK (the selected one didn't work)

The ongoing issue are the local paths in "signingConfigs" but that's easy to comment out.

### CODE REVIEW

**Comment by glKarin** [comment]
Thanks.

**Comment by glKarin** [comment]
I view ETQW source code ago, it has more difference with DOOM3.
Is it possible to port with DOOM3 engine? I think it's not easy.

**Comment by lvonasek** [comment]
I think it is comparable with Prey. I will give it a try and if it is too complex then I give it up.

**Comment by glKarin** [comment]
And in porting, I suggess don't port 64bits first. In jmarshall's porting, some bugs's reason is 64bits support not completed.

**Pull request merged**
