### PR TITLE
[WIP] Linux compatibility

### PR DESCRIPTION
**Pull request by lvonasek**
### Steps done
* ANDROID define moved out of the big CMake, the define is now in the parent jni CMake
* Android specific code compiles on Android only
* On Linux disabled MULTITHREADING, OPENAL and OPENSLES
* Minor compile/linking fixes
* On PC compile executables instead of libraries

### TODOs
- [x] Build libraries on Linux
- [ ] Build executables on Linux
- [ ] Fix Android build
- [ ] OpenAL support
- [ ] Update README.md
- [ ] X11 support

Potentially resolving https://github.com/glKarin/com.n0n3m4.diii4a/issues/96.

### CODE REVIEW

**Review by s0mt0x64 — COMMENTED** [review]
PR has no doxy file

**Comment by lvonasek** [comment]
It is work in progress. I will probably just add a simple readme how to compile it only.

**Review by s0mt0x64 — APPROVED** [review]

**Comment by lvonasek** [comment]
This PR isn't finished yet. It doesn't work yet.

**Comment by glKarin** [comment]
Sorry, I known. But I change some file that exists in this pull request, it causes some conflictions.
I test build Quake4 success on Debian 12, but has some wrong when create X11 window. maybe easier using SDL2 on Linux like dhewm3.

**Comment by lvonasek** [comment]
Ok, thanks. I am actually not so familiar with SDL but it might be good way to go.

I am bit busy these days. Not sure when I find time to continue on this.

**Comment by glKarin** [comment]
However, Quake4 works now on Debian 12 with VirtualBox.
Maybe using mesa OpenGL (X11 soft driver), FPS is very low, so I don't test input control and sound(uising OSS).
Quake4_Debian

**Comment by glKarin** [comment]
TODO:
* with ALSA sound
* enable cURL
* OpenGLES3(missing GLES3 headers)
* OpenAL
* MultiThreading
* Original X11 functions. gamma...

**Comment by lvonasek** [comment]
On my Ubuntu it is pretty smooth. Probably the VM doesn't have a proper 3D acceleration.

**Comment by lvonasek** [comment]
@glKarin does sound work for you? I cannot make it work.

I tried removing NO_ALSA from this line but then it doesn't compile:
https://github.com/glKarin/com.n0n3m4.diii4a/blob/e7e78eac9ae04b7e7789edc944013ca4c7f33f6d/Q3E/src/main/jni/doom3/neo/CMakeLists.txt#L19

**Comment by glKarin** [comment]
I don't test sound, and only compiling successful. I start game in VirtualBox, I only listen noise.

**Review by s0mt0x64 — APPROVED** [review]

**Comment by glKarin** [comment]
Do you try s_useOpenAL to 1 for sound?

**Comment by lvonasek** [comment]
In the latest version there is a small typo (android instead of linux):
https://github.com/glKarin/com.n0n3m4.diii4a/blob/33ceeb05566d490028ab0ab617abfcef07dc80e9/Q3E/src/main/jni/doom3/neo/CMakeLists.txt#L1416

It seems it initializes but then it crashes on segmentation fault. Didn't have enough time to look into it deeper.

**Comment by glKarin** [comment]
OpenAL? need set openal-soft library path with s_libOpenal

**Comment by lvonasek** [comment]
It is crashing with ALSA only. The sound works for me after I changed this to 1:
https://github.com/glKarin/com.n0n3m4.diii4a/blob/05456652b6d36d978e88536c05413a7c2b4ca45c/Q3E/src/main/jni/doom3/neo/sound/snd_system.cpp#L80

To fix compiling of Doom3 remove humanhead from this line:
https://github.com/glKarin/com.n0n3m4.diii4a/blob/05456652b6d36d978e88536c05413a7c2b4ca45c/Q3E/src/main/jni/doom3/neo/CMakeLists.txt#L1528

**Comment by lvonasek** [comment]
After that the main missing thing is the fullscreen support which you can resolving by putting on this line:
https://github.com/glKarin/com.n0n3m4.diii4a/blob/05456652b6d36d978e88536c05413a7c2b4ca45c/Q3E/src/main/jni/doom3/neo/sys/linux/gles2.cpp#L605

this code:
```
	if (cvarSystem->GetCVarInteger("r_fullscreen") == 1) {
		XEvent xev;
		Atom wm_state = XInternAtom(dpy, "_NET_WM_STATE", False);
		Atom fullscreen = XInternAtom(dpy, "_NET_WM_STATE_FULLSCREEN", False);
		memset(&xev, 0, sizeof(xev));
		xev.type = ClientMessage;
		xev.xclient.window = win;
		xev.xclient.message_type = wm_state;
		xev.xclient.format = 32;
		xev.xclient.data.l[0] = 1; // _NET_WM_STATE_ADD
		xev.xclient.data.l[1] = fullscreen;
		xev.xclient.data.l[2] = 0;
		XSendEvent(dpy, DefaultRootWindow(dpy), False, SubstructureNotifyMask | SubstructureRedirectMask, &xev);
		Screen *screen = ScreenOfDisplay(dpy, 0);
		glConfig.vidWidth = actualWidth = screen->width;
		glConfig.vidHeight = actualHeight = screen->height;
	}
```

**Comment by glKarin** [comment]
> It is crashing with ALSA only. The sound works for me after I changed this to 1:
> 
> https://github.com/glKarin/com.n0n3m4.diii4a/blob/05456652b6d36d978e88536c05413a7c2b4ca45c/Q3E/src/main/jni/doom3/neo/sound/snd_system.cpp#L80
> 
> To fix compiling of Doom3 remove humanhead from this line (keep src_core):
> 
> https://github.com/glKarin/com.n0n3m4.diii4a/blob/05456652b6d36d978e88536c05413a7c2b4ca45c/Q3E/src/main/jni/doom3/neo/CMakeLists.txt#L1528

1. add +set s_useOpenAL 1 in script or command
2. _humanhead removed
3. fullscreen fixed

**Pull request merged**
